### ISSUE TITLE
Assets don't get installed

### ISSUE THREAD

**Issue by annejan** [AnimalDesign/bolt-shorturl#1]
I had to manually copy them to the `public_html` folder.

**Comment by madc** [comment]
Which version of Bolt are you using? How did you install the extension itself?

**Comment by annejan** [comment]
Using Bolt 2.2.20

Installed via /bolt/extend

**Comment by annejan** [comment]
Could it be a missing bit in `composer.json`
Like: 

```
    "extra": {
        "bolt-assets": "assets"
    }
```

**Comment by madc** [comment]
I have the extension running on a Bolt 2.2 installation and it works, but i think, that i installed in only locally (not using the bolt extension repo). You might me right, adding the `bolt-assets` part could fix it.
Do you think, you could give it a try and propose a PR? Not sure, if i manage to have a closer look this week.

**Comment by madc** [comment]
Fixed with #2. Thank you.
